### ISSUE TITLE
Welcome, do this to confirm your access

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2019/PInfo1#1]
Hello,

Every project member should do the following:
 - ensure that you have access to the repository (read/write) by adding information to the README (clone, change file, commit, push). Make sure to resolve any potential conflicts.
 - reply here after to indicate that everything worked fine 

The finished README file should provide information about your team (team name, project members)

The project leader should close this issue after **every** member replied.

PS: Don't forget to come up with an interesting project. If you really need slides, keep it short (3 slides max)

**Comment by TommasoPeletta** [comment]
I have successfully read and write the repository. Everything seems to work fine.

**Comment by sardinhapatrick** [comment]
I have the access to the repository.
I can read and write in the README.
Clone, change file, commit and push work correctly.

**Comment by Jonathan-Lo-1996** [comment]
I have access to the repository (read/write). Everything worked fine.

**Comment by JinguMastery** [comment]
I have access to the repository to read and write so everything works fine.

**Comment by GuillaumeComte** [comment]
I have access to the repository 
I can read and write in the README
Clone, change file, commit and push work fine

**Comment by AdrienCHABERT** [comment]
Every thing is fine for everybody. I close this issue
